const employee = [
  {
    id: 1,
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        completed: false,
        newTask: true,
        failed: false,
        title: "Task 1",
        description: "Description of Task 1",
        date: "12-08-2023",
        category: "Development",
      },
      {
        active: false,
        completed: true,
        newTask: false,
        failed: true,
        title: "Task 2",
        description: "Description of Task 2",
        date: "21-09-2023",
        category: "Design",
      },
    ],
  },
  {
    id: 2,
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        completed: false,
        newTask: true,
        failed: false,
        title: "Task 1",
        description: "Description of Task 1",
        date: "05-11-2023",
        category: "Testing",
      },
      {
        active: true,
        completed: true,
        newTask: false,
        failed: false,
        title: "Task 2",
        description: "Description of Task 2",
        date: "17-07-2023",
        category: "Management",
      },
    ],
  },
  {
    id: 3,
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        active: false,
        completed: true,
        newTask: false,
        failed: false,
        title: "Task 1",
        description: "Description of Task 1",
        date: "10-10-2023",
        category: "Research",
      },
      {
        active: true,
        completed: false,
        newTask: true,
        failed: true,
        title: "Task 2",
        description: "Description of Task 2",
        date: "03-04-2023",
        category: "Development",
      },
    ],
  },
  {
    id: 4,
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        completed: false,
        newTask: true,
        failed: false,
        title: "Task 1",
        description: "Description of Task 1",
        date: "15-05-2024",
        category: "Design",
      },
      {
        active: false,
        completed: true,
        newTask: false,
        failed: false,
        title: "Task 2",
        description: "Description of Task 2",
        date: "28-02-2023",
        category: "Testing",
      },
    ],
  },
  {
    id: 5,
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        active: false,
        completed: false,
        newTask: true,
        failed: true,
        title: "Task 1",
        description: "Description of Task 1",
        date: "07-06-2023",
        category: "Management",
      },
      {
        active: true,
        completed: false,
        newTask: true,
        failed: false,
        title: "Task 2",
        description: "Description of Task 2",
        date: "13-09-2023",
        category: "Research",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];
